# These are supported funding model platforms

custom: ['https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7ELM486P7XKKG', 'https://github.com/sponsors/v1s1t0r1sh3r3', 'https://www.blockchain.com/btc/address/1NSzwqtBBdo4CrvynPZmd85xfbL7hw3Ptu', 'https://www.buymeacoffee.com/v1s1t0r']
